<a href="https://colab.research.google.com/github/jibinciby/Case_study/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [ ]:
#A Dataframe is a two dimensional labelled table-exactly like a spreadsheet or SQL Table.It has rows(Identified by Index) and coloums(Identified by coloumn labels). Every coloumn of a Dataframe is a Series.

In [ ]:
#creating Dataframes

data={
    "Name":["Amal","Binu","Cathy","Anna","Tom","Ben"],
    "Dept":["English","CS","Maths","Physics","CS","Maths"],
    "Age":[19,20,22,19,20,22],
    "Marks":[85,72,91,68,88,76]
}
df=pd.DataFrame(data)
print(df)

    Name     Dept  Age  Marks
0   Amal  English   19     85
1   Binu       CS   20     72
2  Cathy    Maths   22     91
3   Anna  Physics   19     68
4    Tom       CS   20     88
5    Ben    Maths   22     76

In [ ]:
df1=pd.DataFrame(data,index=["s1","s2","s3","s4","s5","s6"])
print(df1)

     Name     Dept  Age  Marks
s1   Amal  English   19     85
s2   Binu       CS   20     72
s3  Cathy    Maths   22     91
s4   Anna  Physics   19     68
s5    Tom       CS   20     88
s6    Ben    Maths   22     76

In [ ]:
rows=[
    {"Name":"Ann","Mark":85,"Age":20},
    {"Name":"Aswathy", "Mark":67},
    {"Name":"Aby", "Mark":50},
    {"Name":"Amal", "Mark":40},
    {"Name":"Sam", "Mark":30}
]
df=pd.DataFrame(rows)
print(df)

      Name  Mark   Age
0      Ann    85  20.0
1  Aswathy    67   NaN
2      Aby    50   NaN
3     Amal    40   NaN
4      Sam    30   NaN

In [ ]:
'''List of Lists'''
rows=[["Anu",85],["Binu",72],["Cathy",91]]
a=pd.DataFrame(rows,columns=["Name","Marks"])
print(a)

    Name  Marks
0    Anu     85
1   Binu     72
2  Cathy     91

In [ ]:
print("Shape\n",df.shape)
print("Size\n",df.size)
print("Dimension\n",df.ndim)
print("Coloumns\n",df.columns)
print("Index\n",df.index)
print("Dimension\n",df.ndim)
print("Datatype\n",df.dtypes)
print("Values\n",df.values)
print("Transpose\n",df.T)

Shape
 (6, 4)
Size
 24
Dimension
 2
Coloumns
 Index(['Name', 'Dept', 'Age', 'Marks'], dtype='object')
Index
 RangeIndex(start=0, stop=6, step=1)
Dimension
 2
Datatype
 Name     object
Dept     object
Age       int64
Marks     int64
dtype: object
Values
 [['Amal' 'English' 19 85]
 ['Binu' 'CS' 20 72]
 ['Cathy' 'Maths' 22 91]
 ['Anna' 'Physics' 19 68]
 ['Tom' 'CS' 20 88]
 ['Ben' 'Maths' 22 76]]
Transpose
              0     1      2        3    4      5
Name      Amal  Binu  Cathy     Anna  Tom    Ben
Dept   English    CS  Maths  Physics   CS  Maths
Age         19    20     22       19   20     22
Marks       85    72     91       68   88     76

In [ ]:
print(df)

    Name     Dept  Age  Marks
0   Amal  English   19     85
1   Binu       CS   20     72
2  Cathy    Maths   22     91
3   Anna  Physics   19     68
4    Tom       CS   20     88
5    Ben    Maths   22     76

Inspecting Data

In [ ]:
#head
df.head(3)

    Name     Dept  Age  Marks
0   Amal  English   19     85
1   Binu       CS   20     72
2  Cathy    Maths   22     91

In [ ]:
#tail
df.tail(3)

   Name     Dept  Age  Marks
3  Anna  Physics   19     68
4   Tom       CS   20     88
5   Ben    Maths   22     76

In [ ]:
#sample
df.sample(2)

   Name Dept  Age  Marks
4   Tom   CS   20     88
1  Binu   CS   20     72

In [ ]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Dept    6 non-null      object
 2   Age     6 non-null      int64
 3   Marks   6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
#describe
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.333333  80.000000
std     1.366260   9.316652
min    19.000000  68.000000
25%    19.250000  73.000000
50%    20.000000  80.500000
75%    21.500000  87.250000
max    22.000000  91.000000

In [ ]:
#describe(all)
df.describe(include='all')

        Name Dept        Age      Marks
count      6    6   6.000000   6.000000
unique     6    4        NaN        NaN
top     Amal   CS        NaN        NaN
freq       1    2        NaN        NaN
mean     NaN  NaN  20.333333  80.000000
std      NaN  NaN   1.366260   9.316652
min      NaN  NaN  19.000000  68.000000
25%      NaN  NaN  19.250000  73.000000
50%      NaN  NaN  20.000000  80.500000
75%      NaN  NaN  21.500000  87.250000
max      NaN  NaN  22.000000  91.000000

In [ ]:
#nunique
df.nunique()

Name     6
Dept     4
Age      3
Marks    6
dtype: int64

In [ ]:
print(df)

    Name     Dept  Age  Marks
0   Amal  English   19     85
1   Binu       CS   20     72
2  Cathy    Maths   22     91
3   Anna  Physics   19     68
4    Tom       CS   20     88
5    Ben    Maths   22     76

In [ ]:
#selecting  one coloumn- it is a series
df.columns

print(type(df["Marks"]))
print((df["Marks"]))


print(type(df[["Marks"]]))

<class 'pandas.core.series.Series'>
0    85
1    72
2    91
3    68
4    88
5    76
Name: Marks, dtype: int64
<class 'pandas.core.frame.DataFrame'>

In [4]:
#Exercises
products={
    "Product":["Pen","Notebook","Bag","Bottle","Marker"],
    "Price":[10,45,650,120,30],
    "Stock":[200,45,55,23,12]
}

In [5]:
#1.Create a Dataframe pdf from the dictionary products using the labels p1 to p5 as the row index and print it.
pdf=pd.DataFrame(products,index=['p1','p2','p3','p4','p5'])
print(pdf)

     Product  Price  Stock
p1       Pen     10    200
p2  Notebook     45     45
p3       Bag    650     55
p4    Bottle    120     23
p5    Marker     30     12

In [6]:
#2.For pdf display (a) its shape, (b) the columns names and (c) the datatypes of every coloumn.
print("shape\n",pdf.shape)
print("columns\n",pdf.columns)
print("dtype\n",pdf.dtypes)

shape
 (5, 3)
columns
 Index(['Product', 'Price', 'Stock'], dtype='object')
dtype
 Product    object
Price       int64
Stock       int64
dtype: object

In [7]:
#3.Display the first 3 rows and last 2 rows of pdf.
print("1st 3 rows:\n", pdf.head(3))
print("last 2 rows:\n",pdf.tail(2))

1st 3 rows:
      Product  Price  Stock
p1       Pen     10    200
p2  Notebook     45     45
p3       Bag    650     55
last 2 rows:
    Product  Price  Stock
p4  Bottle    120     23
p5  Marker     30     12

In [8]:
#4.Create a DataFrame from this list of dictionaries and display it:
#[{'Emp':'Ravi','Salary':42000},{'Emp':'Sara','Salary':51000,'City':'Kochi'},{'Emp':'Tom','Salary':38000}]
a=[{'Emp':'Ravi','Salary':42000},
 {'Emp':'Sara','Salary':51000,'City':'Kochi'},
  {'Emp':'Tom','Salary':38000}]
df=pd.DataFrame(a)
print(df)

    Emp  Salary   City
0  Ravi   42000    NaN
1  Sara   51000  Kochi
2   Tom   38000    NaN

In [26]:
#5.Extract the price coloumn of pdf as a series.Display its type, its mean, and the maximum value.Then display the product and stock columns together as a DataFrame.
print(pdf.columns)

a=pdf['Price']
print('price column:\n',a)
print('datatype:',a.dtypes)
print('mean:',a.mean())
print('maximum value:',a.max())

print('product and stock columns:\n',pdf[['Product','Stock']])

Index(['Product', 'Price', 'Stock'], dtype='object')
price column:
 p1     10
p2     45
p3    650
p4    120
p5     30
Name: Price, dtype: int64
datatype: int64
mean: 171.0
maximum value: 650
product and stock columns:
      Product  Stock
p1       Pen    200
p2  Notebook     45
p3       Bag     55
p4    Bottle     23
p5    Marker     12

In [31]:
#6.Use describe() on pdf and state which product-related statistic tells you the typical (median) price.
print(pdf.describe())
print('median price is:',pdf['Price'].median())

            Price       Stock
count    5.000000    5.000000
mean   171.000000   67.000000
std    270.979704   76.285647
min     10.000000   12.000000
25%     30.000000   23.000000
50%     45.000000   45.000000
75%    120.000000   55.000000
max    650.000000  200.000000
median price is: 45.0