<a href="https://colab.research.google.com/github/jibinciby/Case_study/blob/main/Freshmartcase_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import files
uploaded= files.upload()

Saving Retail_Sales.csv to Retail_Sales.csv

In [4]:
df=pd.read_csv("Retail_Sales.csv")

In [ ]:
#1.Load Retail_Sales.csv into a DataFrame named df. Display the first 5 rows and the last 5 rows
df.head()

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
0,ORD1084,Sanjay,Male,Electronics,North,1,20507.70,7.0,5.0,2026-03-23
1,ORD1080,Rahul,Male,Electronics,East,2,4631.95,14.0,5.0,2026-02-11
2,ORD1089,Athira,Female,Grocery,West,6,352.60,12.0,3.0,2026-03-01
3,ORD1036,Sreya,Female,Home,East,4,4582.04,8.0,2.0,2026-03-08
4,ORD1050,Farhan,Male,Grocery,West,1,202.73,12.0,5.0,2026-01-11

In [ ]:
df.tail()

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
90,ORD1083,Kiran,Male,Home,North,3,2488.81,16.0,5.0,2026-01-27
91,ORD1034,Remya,Female,Grocery,South,4,392.58,8.0,NaN,2026-04-22
92,ORD1087,Midhun,Male,Electronics,South,2,9134.12,4.0,3.0,2026-03-25
93,ORD1009,Gopika,Female,Grocery,West,1,164.47,7.0,3.0,2026-03-03
94,ORD1081,Remya,Female,Clothing,East,4,1339.89,13.0,2.0,2026-06-29

In [ ]:
#2.Display one random row from the DataFrame, using a random seed of 1 so that the result is reproducible.
random=df.sample(random_state=1)
print("random row:\n",random)

random row:
     OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
40  ORD1062    Sreya  Female  Electronics  North         2   10057.13

    Discount  Rating   OrderDate
40      14.0     4.0  2026-03-27

In [ ]:
#3.State the number of rows and columns in the DataFrame, and list all column names.
print("no of rows and cloumns: ",df.shape)
print("coumn names:\n ",df.columns)

no of rows and cloumns:  (95, 10)
coumn names:
  Index(['OrderID', 'Customer', 'Gender', 'Category', 'Region', 'Quantity',
       'UnitPrice', 'Discount', 'Rating', 'OrderDate'],
      dtype='object')

In [ ]:
#4.Show the data type of every column and the concise summary of the DataFrame. Identify the columns that have fewer non-null values than the total number of rows.
print("data types of columns:\n",df.dtypes)
print()
print("summary of dataframe:\n",df.describe(include="all"))
print()
print("the columns that have fewer non-null values than the total number of rows\n",df.info())

data types of columns:
 OrderID       object
Customer      object
Gender        object
Category      object
Region        object
Quantity       int64
UnitPrice    float64
Discount     float64
Rating       float64
OrderDate     object
dtype: object

summary of dataframe:
         OrderID Customer Gender Category Region   Quantity     UnitPrice  \
count        95       95     95       95     95  95.000000     95.000000
unique       90       29      2        4      4        NaN           NaN
top     ORD1080   Athira   Male  Grocery   East        NaN           NaN
freq          2        5     48       38     30        NaN           NaN
mean        NaN      NaN    NaN      NaN    NaN   3.452632   4167.508211
std         NaN      NaN    NaN      NaN    NaN   6.105053   6163.461567
min         NaN      NaN    NaN      NaN    NaN   1.000000     46.080000
25%         NaN      NaN    NaN      NaN    NaN   1.000000    239.580000
50%         NaN      NaN    NaN      NaN    NaN   2.000000   1339.890000
75%         NaN      NaN    NaN      NaN    NaN   4.000000   4631.950000
max         NaN      NaN    NaN      NaN    NaN  60.000000  24239.260000

         Discount     Rating   OrderDate
count   89.000000  86.000000          95
unique        NaN        NaN          67
top           NaN        NaN  2026-04-21
freq          NaN        NaN           3
mean    11.269663   3.151163         NaN
std      5.078395   1.459391         NaN
min      2.000000   1.000000         NaN
25%      7.000000   2.000000         NaN
50%     11.000000   3.000000         NaN
75%     14.000000   5.000000         NaN
max     25.000000   5.000000         NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    95 non-null     object
 1   Customer   95 non-null     object
 2   Gender     95 non-null     object
 3   Category   95 non-null     object
 4   Region     95 non-null     object
 5   Quantity   95 non-null     int64
 6   UnitPrice  95 non-null     float64
 7   Discount   89 non-null     float64
 8   Rating     86 non-null     float64
 9   OrderDate  95 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 7.6+ KB
the columns that have fewer non-null values than the total number of rows
 None

In [ ]:
#5,Generate the summary statistics for the numeric columns, and then for all columns including text columns.
print("summary for numeric columns:\n",df.describe())
print()
print("summary for all columns:\n",df.describe(include='all'))

summary for numeric columns:
         Quantity     UnitPrice   Discount     Rating
count  95.000000     95.000000  89.000000  86.000000
mean    3.452632   4167.508211  11.269663   3.151163
std     6.105053   6163.461567   5.078395   1.459391
min     1.000000     46.080000   2.000000   1.000000
25%     1.000000    239.580000   7.000000   2.000000
50%     2.000000   1339.890000  11.000000   3.000000
75%     4.000000   4631.950000  14.000000   5.000000
max    60.000000  24239.260000  25.000000   5.000000

summary for all columns:
         OrderID Customer Gender Category Region   Quantity     UnitPrice  \
count        95       95     95       95     95  95.000000     95.000000
unique       90       29      2        4      4        NaN           NaN
top     ORD1080   Athira   Male  Grocery   East        NaN           NaN
freq          2        5     48       38     30        NaN           NaN
mean        NaN      NaN    NaN      NaN    NaN   3.452632   4167.508211
std         NaN      NaN    NaN      NaN    NaN   6.105053   6163.461567
min         NaN      NaN    NaN      NaN    NaN   1.000000     46.080000
25%         NaN      NaN    NaN      NaN    NaN   1.000000    239.580000
50%         NaN      NaN    NaN      NaN    NaN   2.000000   1339.890000
75%         NaN      NaN    NaN      NaN    NaN   4.000000   4631.950000
max         NaN      NaN    NaN      NaN    NaN  60.000000  24239.260000

         Discount     Rating   OrderDate
count   89.000000  86.000000          95
unique        NaN        NaN          67
top           NaN        NaN  2026-04-21
freq          NaN        NaN           3
mean    11.269663   3.151163         NaN
std      5.078395   1.459391         NaN
min      2.000000   1.000000         NaN
25%      7.000000   2.000000         NaN
50%     11.000000   3.000000         NaN
75%     14.000000   5.000000         NaN
max     25.000000   5.000000         NaN

In [ ]:
#6.Find the mean, median and mode of Quantity. Compare the mean and the median and state what the comparison indicates about the distribution.
print("mean of Quantity:",df["Quantity"].mean())
print("median of Quantity:",df["Quantity"].median())
print("mode of Qunatity:",df["Quantity"].mode())

mean of Quantity: 3.4526315789473685
median of Quantity: 2.0
mode of Qunatity: 0    1
Name: Quantity, dtype: int64

In [ ]:
#7.Find the minimum, maximum and standard deviation of UnitPrice.
print("minimum of Unitprice:",df["UnitPrice"].min())
print("maximum of Unitprice:",df["UnitPrice"].max())
print("standard deviation of Unitprice:",df["UnitPrice"].std())

minimum of Unitprice: 46.08
maximum of Unitprice: 24239.26
standard deviation of Unitprice: 6163.4615671521515

In [ ]:
#8.Count the non-null values in every column of the DataFrame. Explain any differences you observe between columns. Then compute the total number of units sold.
df.notnull().sum()

OrderID      95
Customer     95
Gender       95
Category     95
Region       95
Quantity     95
UnitPrice    95
Discount     89
Rating       86
OrderDate    95
dtype: int64

In [ ]:
#9.For the Category column, list the unique values, the number of unique values, the count of each value and the percentage share of each value.
print("unique values:",df["Category"].unique())
print()
print("no of unique values:",df["Category"].nunique())
print()
print("count of each values:\n",df["Category"].value_counts())
print()
print("percentage share of each values:\n",df["Category"].value_counts(normalize=True)*100)

unique values: ['Electronics' 'Grocery' 'Home' 'Clothing']

no of unique values: 4

count of each values:
 Category
Grocery        38
Electronics    29
Clothing       17
Home           11
Name: count, dtype: int64

percentage share of each values:
 Category
Grocery        40.000000
Electronics    30.526316
Clothing       17.894737
Home           11.578947
Name: proportion, dtype: float64

In [ ]:
#10.Repeat the analysis for the Region column. Identify the region with the most orders.
region=df["Region"].value_counts().idxmax()
print("Region with most orders:",region)

Region with most orders: East

In [ ]:
#11.Count the missing values in each column, the total number of missing values, and the percentage of missing values in each column.
print("missing values in each column:\n",df.isnull().sum())
print()
print("total missing values:",df.isnull().sum().sum())

missing values in each column:
 OrderID      0
Customer     0
Gender       0
Category     0
Region       0
Quantity     0
UnitPrice    0
Discount     6
Rating       9
OrderDate    0
dtype: int64

total missing values: 15

In [ ]:
#12.Determine how many rows would be lost if every row containing a missing value were removed (do not modify df). Justify whether removal is an appropriate choice for this dataset
print("no of rows that would be lost:",df.isnull().any(axis=1).sum())

#so, fillna(0) will be more applicable than removing rows.

no of rows that would be lost: 15

In [ ]:
#13.Treat the missing values in Discount and Rating using methods you consider appropriate. Save the changes in df, confirm that no missing values remain, and justify your choice of method for each column.
print("missing values in Discount:",df["Discount"].isnull().sum())
print("missing values in Rating:",df["Rating"].isnull().sum())

missing values in Discount: 6
missing values in Rating: 9

In [ ]:
df["Discount"]=df["Discount"].fillna(df["Discount"].median())
df["Rating"]=df["Rating"].fillna(df["Rating"].median())

print("missing values in Discount after changes:",df["Discount"].isnull().sum())
print("missing values in Rating after changes:",df["Rating"].isnull().sum())

missing values in Discount after changes: 0
missing values in Rating after changes: 0

In [ ]:
#14.Count the duplicate rows. Display every row that belongs to a duplicate group, including the first occurrence, sorted by OrderID.
duplicates=df[df.duplicated(keep=False)]
duplicates = duplicates.sort_values(by="OrderID")
print(duplicates)

    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
24  ORD1029  Lakshmi  Female  Electronics   East         1    2659.08
69  ORD1029  Lakshmi  Female  Electronics   East         1    2659.08
68  ORD1034    Remya  Female      Grocery  South         4     392.58
91  ORD1034    Remya  Female      Grocery  South         4     392.58
45  ORD1077    Arjun    Male      Grocery   West         6     137.52
47  ORD1077    Arjun    Male      Grocery   West         6     137.52
1   ORD1080    Rahul    Male  Electronics   East         2    4631.95
55  ORD1080    Rahul    Male  Electronics   East         2    4631.95
58  ORD1087   Midhun    Male  Electronics  South         2    9134.12
92  ORD1087   Midhun    Male  Electronics  South         2    9134.12

    Discount  Rating   OrderDate
24       7.0     5.0  2026-04-21
69       7.0     5.0  2026-04-21
68       8.0     3.0  2026-04-22
91       8.0     3.0  2026-04-22
45      12.0     4.0  2026-04-09
47      12.0     4.0  2026-04-09
1       14.0     5.0  2026-02-11
55      14.0     5.0  2026-02-11
58       4.0     3.0  2026-03-25
92       4.0     3.0  2026-03-25

In [ ]:
#15.Remove the duplicate records, save the result in df, and confirm the new shape of the DataFrame.
df=df.drop_duplicates()
print(df)
print()
print("new shape:",df.shape)

    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
0   ORD1084   Sanjay    Male  Electronics  North         1   20507.70
1   ORD1080    Rahul    Male  Electronics   East         2    4631.95
2   ORD1089   Athira  Female      Grocery   West         6     352.60
3   ORD1036    Sreya  Female         Home   East         4    4582.04
4   ORD1050   Farhan    Male      Grocery   West         1     202.73
..      ...      ...     ...          ...    ...       ...        ...
88  ORD1075   Athira  Female      Grocery  South         6     150.19
89  ORD1082   Anjali  Female     Clothing  South         3    2827.45
90  ORD1083    Kiran    Male         Home  North         3    2488.81
93  ORD1009   Gopika  Female      Grocery   West         1     164.47
94  ORD1081    Remya  Female     Clothing   East         4    1339.89

    Discount  Rating   OrderDate
0        7.0     5.0  2026-03-23
1       14.0     5.0  2026-02-11
2       12.0     3.0  2026-03-01
3        8.0     2.0  2026-03-08
4       12.0     5.0  2026-01-11
..       ...     ...         ...
88      17.0     3.0  2026-01-27
89      16.0     3.0  2026-04-21
90      16.0     5.0  2026-01-27
93       7.0     3.0  2026-03-03
94      13.0     2.0  2026-06-29

[90 rows x 10 columns]

new shape: (90, 10)

In [ ]:
#16.OrderDate is stored as text. Convert it to a proper date data type. Some entries may not be valid dates; handle them so that the conversion does not fail, and report how many invalid dates were found.
df['OrderDate']=pd.to_datetime(df['OrderDate'],errors='coerce')
invalid_dates = df['OrderDate'].isna().sum()
print(df['OrderDate'])
print()
print("no of invalid dates:",invalid_dates)

0    2026-03-23
1    2026-02-11
2    2026-03-01
3    2026-03-08
4    2026-01-11
        ...
90   2026-01-27
91   2026-04-22
92   2026-03-25
93   2026-03-03
94   2026-06-29
Name: OrderDate, Length: 95, dtype: datetime64[ns]

no of invalid dates: 2

In [ ]:
#17.Convert Category and Region to the string data type and Quantity to a floating-point type. Print the data types to verify.
df['Category']=df['Category'].astype(str)
df['Region']=df['Region'].astype(str)
df['Quantity']=df['Quantity'].astype(float)
print(df['Category'].dtypes)
print(df['Region'].dtypes)
print(df['Quantity'].dtypes)

object
object
float64

In [ ]:
#18.Create the DataFrame below, in which Age is stored as text. Convert Age to integers. Then take a column that contains the text 'abc' among numeric strings and convert it to numeric without the program raising an error. Explain the difference in behaviour between the two conversion approaches you used.	[3] small = pd.DataFrame({'Name':['Anu','Rahul','Meera'], 'Age':['20','21','22']})
small = pd.DataFrame({'Name':['Anu','Rahul','Meera'], 'Age':['20','21','22']})
small['Age']=small['Age'].astype(int)
small['Marks']=['85','abc','90']
small['Marks'] = pd.to_numeric(small['Marks'], errors='coerce')
print(small['Marks'])

#astype(int) raises an error for invalid text, whereas pd.to_numeric(errors='coerce') replaces invalid values with NaN and continues execution.

0    85.0
1     NaN
2    90.0
Name: Marks, dtype: float64

In [ ]:
#19.Show all orders where Quantity is greater than 5.
print(df[df['Quantity'] > 5])

    OrderID Customer  Gender  Category Region  Quantity  UnitPrice  Discount  \
2   ORD1089   Athira  Female   Grocery   West       6.0     352.60      12.0
18  ORD1005     Manu    Male   Grocery  South       6.0     239.34      22.0
33  ORD1028     Neha  Female  Clothing   East       6.0     480.23      17.0
35  ORD1042   Joseph    Male   Grocery   East       6.0     262.10      12.0
41  ORD1027    Arjun    Male   Grocery   West       6.0      71.02      22.0
45  ORD1077    Arjun    Male   Grocery   West       6.0     137.52      12.0
47  ORD1077    Arjun    Male   Grocery   West       6.0     137.52      12.0
63  ORD1002     Neha  Female   Grocery   East       6.0      86.72      22.0
65  ORD1086    Sreya  Female   Grocery   East       6.0     228.99      22.0
75  ORD1018    Basil    Male   Grocery  South      60.0     120.00      25.0
80  ORD1054    Divya  Female      Home  South       6.0    3645.08      12.0
88  ORD1075   Athira  Female   Grocery  South       6.0     150.19      17.0

    Rating  OrderDate
2      3.0 2026-03-01
18     3.0 2026-06-28
33     5.0 2026-06-25
35     3.0 2026-02-20
41     3.0 2026-05-04
45     4.0 2026-04-09
47     4.0 2026-04-09
63     5.0 2026-06-27
65     2.0 2026-03-29
75     1.0 2026-04-07
80     4.0 2026-01-10
88     3.0 2026-01-27

In [ ]:
#20.Show all orders where Rating is below 3, displaying only the columns OrderID, Category and Rating.
print(df.loc[df['Rating']<3, ['OrderID','Category','Rating']])

    OrderID     Category  Rating
3   ORD1036         Home     2.0
8   ORD1060  Electronics     2.0
10  ORD1068     Clothing     2.0
11  ORD1076      Grocery     1.0
12  ORD1056  Electronics     1.0
14  ORD1011     Clothing     1.0
16  ORD1070         Home     1.0
17  ORD1003  Electronics     2.0
20  ORD1012      Grocery     1.0
27  ORD1032      Grocery     2.0
29  ORD1015      Grocery     1.0
32  ORD1013         Home     1.0
36  ORD1001  Electronics     1.0
37  ORD1026  Electronics     2.0
38  ORD1088  Electronics     2.0
39  ORD1055      Grocery     2.0
42  ORD1020     Clothing     1.0
43  ORD1031  Electronics     2.0
49  ORD1016  Electronics     2.0
50  ORD1037     Clothing     1.0
53  ORD1065      Grocery     2.0
54  ORD1072     Clothing     2.0
59  ORD1040  Electronics     1.0
64  ORD1052      Grocery     1.0
65  ORD1086      Grocery     2.0
67  ORD1046  Electronics     2.0
71  ORD1058  Electronics     1.0
75  ORD1018      Grocery     1.0
77  ORD1017         Home     2.0
82  ORD1061     Clothing     1.0
83  ORD1057         Home     2.0
94  ORD1081     Clothing     2.0

In [ ]:
#21.Sort all orders by UnitPrice from highest to lowest and display the top 5 rows.
print(df.sort_values(by='UnitPrice',ascending=False).head(5))

    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
12  ORD1056    Ajith    Male  Electronics  South       2.0   24239.26
51  ORD1059    Basil    Male  Electronics   West       2.0   22650.65
59  ORD1040   Midhun    Male  Electronics   West       2.0   22211.38
49  ORD1016  Keerthi  Female  Electronics  South       2.0   21543.62
0   ORD1084   Sanjay    Male  Electronics  North       1.0   20507.70

    Discount  Rating  OrderDate
12      14.0     1.0 2026-02-14
51       NaN     5.0 2026-03-03
59       9.0     1.0 2026-04-02
49      14.0     2.0 2026-02-14
0        7.0     5.0 2026-03-23

In [ ]:
#22.Without sorting the entire DataFrame, find the 5 orders with the highest Quantity.
print(df.sort_values(by='Quantity',ascending=False).head(5))

    OrderID Customer  Gender Category Region  Quantity  UnitPrice  Discount  \
75  ORD1018    Basil    Male  Grocery  South      60.0     120.00      25.0
18  ORD1005     Manu    Male  Grocery  South       6.0     239.34      22.0
2   ORD1089   Athira  Female  Grocery   West       6.0     352.60      12.0
35  ORD1042   Joseph    Male  Grocery   East       6.0     262.10      12.0
45  ORD1077    Arjun    Male  Grocery   West       6.0     137.52      12.0

    Rating  OrderDate
75     1.0 2026-04-07
18     3.0 2026-06-28
2      3.0 2026-03-01
35     3.0 2026-02-20
45     4.0 2026-04-09

In [ ]:
#23.Find the average Quantity for each Category.
a=df.groupby('Category')['Quantity'].mean()
print(a)

Category
Clothing       3.294118
Electronics    1.620690
Grocery        5.052632
Home           3.000000
Name: Quantity, dtype: float64

In [ ]:
#24.For each Category, show the count, mean, median, minimum and maximum of UnitPrice in a single table.
a=df.groupby('Category')['UnitPrice'].agg(['mean','median','min','max'])
print(a)

                     mean   median      min       max
Category
Clothing      1425.132941  1339.89   431.57   2885.12
Electronics  11146.940690  9134.12  2659.08  24239.26
Grocery        199.986579   191.40    46.08    392.58
Home          3711.386364  3645.08   942.68   5657.83

In [ ]:
#25.Find the average Rating for each Region and for each Gender. State which region is rated best.
reg=df.groupby('Region')['Rating'].mean()
print(reg)
print()
gen=df.groupby('Gender')['Rating'].mean()
print(gen)
print()
print("region rated best:",reg.idxmax())

Region
East     3.241379
North    3.368421
South    2.714286
West     3.294118
Name: Rating, dtype: float64

Gender
Female    3.047619
Male      3.250000
Name: Rating, dtype: float64

region rated best: North

In [ ]:
#26.Find the correlation between Quantity and Discount, and between UnitPrice and Rating. State which relationship is stronger and give a possible reason.
co1=df['Quantity'].corr(df['Discount'])
print("correlation between Quantity and Discount:",co1)
co2=df['UnitPrice'].corr(df['Rating'])
print("correlation between Unitprice and Rating:",co2)
if co1>co2:
  print("Correlation between Quantity and Discount is stronger.")
else:
  print("correlation between Unitprice and Rating is stronger.")

correlation between Quantity and Discount: 0.4499707867007552
correlation between Unitprice and Rating: -0.09359210285877759
Correlation between Quantity and Discount is stronger.

In [7]:
#27.Use the Interquartile Range (IQR) method to identify outliers in Quantity. Print Q1, Q3, the lower and upper limits, and the outlier rows.
Q1=df["Quantity"].quantile(0.25)
Q3=df["Quantity"].quantile(0.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

outliers=df[
    (df["Quantity"]<lower) |
    (df["Quantity"]>upper)
    ]
print(outliers)
print()

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower)
print("Upper Limit:", upper)

    OrderID Customer Gender Category Region  Quantity  UnitPrice  Discount  \
75  ORD1018    Basil   Male  Grocery  South        60      120.0      25.0

    Rating   OrderDate
75     1.0  2026-04-07

Q1: 1.0
Q3: 4.0
IQR: 3.0
Lower Limit: -3.5
Upper Limit: 8.5

In [8]:
#28.Examine the outlier rows and decide whether they are genuine or data-entry errors, giving your reasoning. Create a DataFrame named df_clean that excludes the rows you judge to be errors, and compare the mean of Quantity before and after.
print(outliers)

print()
df_clean = df.drop(outliers.index)
mean_before = df['Quantity'].mean()
mean_after = df_clean['Quantity'].mean()
print("Mean Quantity Before Cleaning:", mean_before)
print("Mean Quantity After Cleaning:", mean_after)

    OrderID Customer Gender Category Region  Quantity  UnitPrice  Discount  \
75  ORD1018    Basil   Male  Grocery  South        60      120.0      25.0

    Rating   OrderDate
75     1.0  2026-04-07

Mean Quantity Before Cleaning: 3.4526315789473685
Mean Quantity After Cleaning: 2.851063829787234

In [9]:
#29.Use df_clean from this point onwards. Create a column Gross (Quantity x UnitPrice) and a column Revenue, which is Gross after applying the Discount percentage.
df_clean['Gross'] = df_clean['Quantity'] * df_clean['UnitPrice']
df_clean['Revenue'] = df_clean['Gross'] - (df_clean['Gross'] * df_clean['Discount'] / 100)
print(df_clean[['Quantity', 'UnitPrice', 'Discount', 'Gross', 'Revenue']])

    Quantity  UnitPrice  Discount     Gross     Revenue
0          1   20507.70       7.0  20507.70  19072.1610
1          2    4631.95      14.0   9263.90   7966.9540
2          6     352.60      12.0   2115.60   1861.7280
3          4    4582.04       8.0  18328.16  16861.9072
4          1     202.73      12.0    202.73    178.4024
..       ...        ...       ...       ...         ...
90         3    2488.81      16.0   7466.43   6271.8012
91         4     392.58       8.0   1570.32   1444.6944
92         2    9134.12       4.0  18268.24  17537.5104
93         1     164.47       7.0    164.47    152.9571
94         4    1339.89      13.0   5359.56   4662.8172

[94 rows x 5 columns]

In [10]:
#30.Create a column Order_Size classifying each order as 'Large' if Revenue is at least 10000, 'Medium' if Revenue is at least 2000 but below 10000, and 'Small' otherwise. Count the orders in each size class.
import numpy as np
df_clean['Order_Size'] = np.where(df_clean['Revenue'] >= 10000, 'Large',np.where(df_clean['Revenue'] >= 2000, 'Medium', 'Small'))
print(df_clean['Order_Size'].value_counts())

Order_Size
Small     47
Medium    24
Large     23
Name: count, dtype: int64

In [ ]:
#31.Find the top 5 orders by Revenue and the total Revenue for each Category.
top5 = df_clean.sort_values(by='Revenue', ascending=False).head(5)
print("Top 5 Orders by Revenue:")
print(top5)
print()
cat_revenue = df_clean.groupby('Category')['Revenue'].sum()
print("Total Revenue for each Category:")
print(cat_revenue)

Top 5 Orders by Revenue:
    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
12  ORD1056    Ajith    Male  Electronics  South         2   24239.26
59  ORD1040   Midhun    Male  Electronics   West         2   22211.38
49  ORD1016  Keerthi  Female  Electronics  South         2   21543.62
8   ORD1060  Keerthi  Female  Electronics  South         2   13809.19
38  ORD1088     Manu    Male  Electronics  South         2   12667.99

    Discount  Rating   OrderDate     Gross     Revenue Order_Size
12      14.0     1.0  2026-02-14  48478.52  41691.5272      Large
59       9.0     1.0  2026-04-02  44422.76  40424.7116      Large
49      14.0     2.0  2026-02-14  43087.24  37055.0264      Large
8        9.0     2.0  2026-04-16  27618.38  25132.7258      Large
38      14.0     2.0  2026-06-18  25335.98  21788.9428      Large

Total Revenue for each Category:
Category
Clothing        66037.6964
Electronics    406018.1927
Grocery         21788.3590
Home            98404.4397
Name: Revenue, dtype: float64

In [11]:
#32.Save df_clean as cleaned_retail.csv without the index column. Reload the file and print its shape to verify.
df_clean.to_csv('cleaned_retail.csv', index=False)
df_reloaded = pd.read_csv('cleaned_retail.csv')
print(df_reloaded.shape)

(94, 13)

In [12]:
#33.Which Category brings the highest total Revenue, and which Region sells the most?
cat_revenue = df_clean.groupby('Category')['Revenue'].sum()
print("Category with Highest Revenue:",cat_revenue.idxmax())
region_sales = df_clean.groupby('Region')['Revenue'].sum()
print("\nRegion with Highest Sales:",region_sales.idxmax())

Category with Highest Revenue: Electronics

Region with Highest Sales: South

In [14]:
#34.Does a higher Discount appear to increase the Quantity bought? Support your answer with a numerical value from your analysis.
correlation = df_clean['Discount'].corr(df_clean['Quantity'])
print("Correlation between Discount and Quantity:", correlation)

#Yes. A higher Discount appears to be associated with a higher Quantity bought.

Correlation between Discount and Quantity: 0.6558728543467195

In [ ]:
#35.Explain why you chose your particular method for treating the missing Rating values.

#I chose to replace the missing values in the Rating column with the median because the median is less affected by outliers than the mean.

In [15]:
#36.Write a summary of 3-4 lines of your findings for the sales manager.


#The sales analysis shows that revenue varies across different product categories and regions, helping identify the strongest sales performers.
#The top 5 orders contribute significantly to overall revenue.
#A positive correlation of 0.6559 between Discount and Quantity indicates that higher discounts are associated with higher quantities purchased.
#The business can use these insights to improve discount strategies, focus on high-performing categories and regions, and increase overall sales.